from typing import List, TypedDict, Annotated, Optional, Dict, Any
from langchain_core.documents import Document
import operator

class AgentState(TypedDict):
    """
    Represents the shared global state of the LangGraph workflow.
    This dictionary is passed between nodes (Planner, Retriever, Synthesizer) 
    to maintain context and drive the agentic decision-making process.
    """
    
    # The original natural language question entered by the user.
    query: str 
    
    # The structured retrieval strategy generated by the Planner Agent.
    # Includes query_type, metadata_filters, and architectural reasoning.
    plan: Optional[Dict[str, Any]]
    
    # A list of decomposed, atomic sub-queries derived from the original query 
    # to handle complex or multi-part questions.
    optimized_queries: List[str] 
    
    # A cumulative list of retrieved LangChain Document objects.
    # 'operator.add' ensures that new documents are appended to the list 
    # rather than overwriting existing ones during multi-pass retrieval.
    documents: Annotated[List[Document], operator.add]
    
    # A single string containing the merged page_content from all retrieved 
    # documents, formatted for the Synthesizer's LLM prompt.
    retriever_content: str 
    
    # Boolean flag indicating if the Retriever successfully found relevant 
    # document chunks in the vector database.
    retrieval_success: bool
    
    # The final natural language response generated by the Synthesizer Agent.
    generation: str
    
    # Guidance or instructions provided to agents during iterative cycles 
    # (e.g., "Initial attempt" or "Search missed X, try Y").
    revision_notes: str
    
    # Tracks the number of loops through the graph to prevent infinite 
    # execution and manage recursive agentic patterns.
    retry_count: int 
    
    # A numerical value (0.0 to 1.0) representing the system's confidence 
    # in the factual accuracy and grounding of the generated answer.
    confidence_score: float