import logging
from ingestion.data_ingestion import create_vector_store
from agents.agent_graph import build_workflow

# Configure logging to capture the internal "thinking" process of the agents
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("RAG_Orchestrator")

def run_agent(query: str, pdf_path: str):
    """
    Orchestrates the end-to-end RAG process including document ingestion,
    graph initialization, and agent execution.

    Args:
        query (str): The user's natural language question.
        pdf_path (str): Path to the source document for grounding.
    """
    try:
        # Step 1: Document Processing (Commented out if using persistent vector store)
        logger.info(f"Ingesting document: {pdf_path}")
        create_vector_store(pdf_file_name=pdf_path)

        # Step 2: Build the LangGraph State Machine
        # This compiles the nodes (Planner, Retriever, Synthesizer) into an executable graph.
        app = build_workflow()

        # Step 3: Define Initial State
        # We initialize retry_count at 0 and provide notes to guide the first iteration.
        initial_inputs = {
            "query": query,
            "revision_notes": "Initial attempt.",
            "retry_count": 0
        }

        logger.info(f"Starting workflow for query: '{query}'")
        
        # Step 4: Execute the Graph
        # .invoke() starts the execution at the entry point defined in the graph.
        final_state = app.invoke(initial_inputs)

        # Step 5: Output Presentation
        # Extract the final answer generated by the Synthesizer node.
        
        return final_state
        

    except Exception as e:
        # Catch and log any errors occurring within the graph execution or setup.
        logger.error(f"An error occurred during agent execution: {e}")

if __name__ == "__main__":
    """
    Entry point for the CLI application. 
    Accepts user input and triggers the RAG orchestration pipeline.
    """
    # Prompt user for their query via the command line interface
    USER_QUERY = input("enter query: ")
    
    # Define the source document (must exist in the data/ folder)
    PDF_FILE_NAME = "rag_pdf.pdf"
    
    # Start the execution
    response = run_agent(USER_QUERY, pdf_path=PDF_FILE_NAME)
    print("\n" + "="*50)
    print("FINAL RESPONSE FROM AGENT:")
    print("="*50)
    print(response.get("generation", "No response generated."))
    print("="*50)